<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\StadiaPass.Application\StadiaPass.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StadiaPass.Infrastructure\StadiaPass.Infrastructure.csproj" />
    <ProjectReference Include="..\..\Infrastructure\StadiaPass.Persistence\StadiaPass.Persistence.csproj" />
    <ProjectReference Include="..\..\Shared\StadiaPass.SharedKernel.AspNetCore\StadiaPass.SharedKernel.AspNetCore.csproj" />
    <ProjectReference Include="..\..\..\orchestrator\StadiaPass.ServiceDefaults\StadiaPass.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Keycloak.Authentication" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
