<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>e1493f1f-fb72-47b7-a2d3-77510eaf3d77</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Presentation\StadiaPass.WebAPI\StadiaPass.WebAPI.csproj" />
    <ProjectReference Include="..\..\src\Presentation\StadiaPass.WebMVC\StadiaPass.WebMVC.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Keycloak" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

</Project>
