<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\Core\StadiaPass.Application\StadiaPass.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Elastic.Clients.Elasticsearch" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
    <PackageReference Include="Stripe.net" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="MailKit" />
  </ItemGroup>

</Project>
